### ISSUE TITLE
Eric Hollis - Peer Code Review - Week 14

### ISSUE THREAD

**Issue by ehollis98** [Norskknight/eggCheckInProject#4]
# Design/Code Review 3

#### Reviewer: Eric Hollis

|Category|Criteria|Rating/Comments|
|--------|---------|---------------|
|**Project Overview**|| Project was reviewed in-person on December 5th 2018, and pulled for individual review on December 7th 2018 at 2:15pm |
||Which planned functionality has been met? | During the in-person code review I was shown working tests for creating, reading, updating, and deleting of both eggs and user entities. When the application was deployed, however, there wasn't a way of accomplishing this via the HTML or JSP pages given. The generation of an egg's wash, refrigeration, and use by date methods appeared to be functioning properly. Aspects from the defined security goals were present, such as username and password fields, but weren't implemented at the time of reviewing. The database was present in it's entirety, with users and their respective roles, as well as eggs accompanied by their dates and types. Hibernate was shown in-person to be working, and was combined with Lombok which I am unfortunately unfamiliar with, but it all worked. All dependencies are in place within the .pom file. All of the shells for the CSS are present, but were empty at the time of review. Logging is in place and working. Unit testing was available for all methods for the GenericDAO for full CRUD on eggs and users, with full test coverage of what was available. |
|| What planned functionality has not been met? | The application does not currently have the ability for users to do anything via the web pages supplied, except navigate between JSP pages at the moment. I didn't see a TagLib implemented at the time of review. There was no security or login capabilities. No CSS present. No Data validation currently. Application not deployed to Amazon Web Services(AWS) yet. |
||Describe the GitHub history and what it demonstrates about the project progress during the semester.| The GitHub history for this project shows that as new material was learned throughout the semester, it was added periodically to the application. It's difficult to review this point as the semester had a lot of content to manage. |
||Describe how peer and instructor feedback/recommendations were incorporated into the project.| Issues were created and placed onto the GitHub page for the developer being peer reviewed.|
||Other comments/notes?| N/A |
|**JSPs**|| |
||Evaluate the JSPs for templating, business logic, data validation, overall look and feel.| At the moment, the JSPs offered are simple links to navigate back and forth between the various pages. CSS still needs to be applied. |
||Other comments/notes?| |
|**Java code quality**|Evaluate the code quality for the following and identify specific areas for improvement (class, method or line number) <li>single-purpose methods <li>well-structured project <li>descriptive naming of packages, classes, methods, variables <li>classes appropriately-sized  (no monster classes) <li> CPD (copy paste detection, meaning are the same lines of code repeated?) <li>are there candidates for super/subclass relationships, abstract classes, interfaces? <li>are any values hard-coded that should be in a properties file? <li>proper exception handling <li>proper error reporting to the user <li> code documentation | The project is well-structured, with properly named directories, and good file categorization. Methods are broken down to perform a single purpose rather than a host of multiple tasks. Classes are sized accordingly for the project. I mentioned that perhaps the values of "Two Weeks" and "One Week" could be constants instead of using a literal '14' or '7' but as it was just for test purposes at this point, it wasn't necessary yet. Some more JavaDoc comments may be needed here and there, as it appears sparse, but otherwise well done. |Other comments/notes?| |
|**Logging**|Evaluate the use of logging, for example:<li>appropriate use of logging statements in the code for error logging and debugging <li>logging levels used - info, debug, error <li> no occurrences of  System.out.printlns or printStackTrace() <li> logging works on AWS deploy| Logging is in place within the application, with no System.out.println's or printStackTrace's. Info level is currently being used for logging. No AWS version available to review. |Other comments/notes?| |
|**Unit Tests**|Evaluate the unit tests, for example: <li>tests are truly a unit test rather than a high level functional test <li>test data is appropriately cleaned up or handled <li> there is full coverage of methods that perform business logic or utility functions <li>redundant code is eliminated by using set up and tear down methods, i.e., @Before, @After | Currently, there is testing for an Egg entity and for the GenericDAO. Full CRUD is tested on the DAO. No setup/teardown methods in place, such as @Before or @After.|
||Other comments/notes?| |
|**Security**|Evaluate authentication/authorization:| Initial variables are in place such as username and password, but no visible functionality is there. |
||Is it implemented correctly and working locally as well as on AWS?| Not implemented locally or on AWS at the time of reviewing. |
||Other comments/notes?| |
|**Web Service/API integration**|Evaluate the service/api integration, for example: <li> Which service/api is implemented? <li>How is  error handling of the service implemented? For example, what happens if the service is not available?| N/A |
||Other comments/notes?| |
|**Independent research topic**| What is the independent research topic?| CSS Grid |
||Is the independent research topic/technique implemented in the project?| The shell for it is, the CSS Grid that was planned is laid out, it just needs the code to get it working at this point. |
||Other comments/notes?| |
|**Deployment**| Has the application been successfully deployed to AWS?| Not currently deployed to AWS. |
||Is the hosted application fully functioning?| N/A |
||Other comments/notes?| |
|**Review Plugins**|SolarLint & QAPlug| SolarLint provided me with the following suggestions: In the GenericDAO class, on line 18, the private field should be removed. On line 44 of GenericDAO, there is a "dead store" for the local variable 'root', meaning it isn't read by any following code. The variable may not be needed in this case. QAPlug gave me: In the Egg class, on line 42, the local variable of 'nextDate' is redundant. In GenericDAO, on line 17, the variable declaration could be 'final' as well. On line 31, the initializer of '0' is redundant.  |

**Comment by pawaitemadisoncollege** [comment]
A through job here @ehollis98!
